#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/motorola/ocean

PRODUCT_COPY_FILES += \
    vendor/motorola/ocean/proprietary/vendor/etc/acdbdata/common/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/common/Bluetooth_cal.acdb \
    vendor/motorola/ocean/proprietary/vendor/etc/acdbdata/common/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/common/General_cal.acdb \
    vendor/motorola/ocean/proprietary/vendor/etc/acdbdata/common/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/common/Global_cal.acdb \
    vendor/motorola/ocean/proprietary/vendor/etc/acdbdata/common/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/common/Handset_cal.acdb \
    vendor/motorola/ocean/proprietary/vendor/etc/acdbdata/common/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/common/Hdmi_cal.acdb \
    vendor/motorola/ocean/proprietary/vendor/etc/acdbdata/common/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/common/Headset_cal.acdb \
    vendor/motorola/ocean/proprietary/vendor/etc/acdbdata/common/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/common/Speaker_cal.acdb \
    vendor/motorola/ocean/proprietary/vendor/etc/acdbdata/na/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/na/Bluetooth_cal.acdb \
    vendor/motorola/ocean/proprietary/vendor/etc/acdbdata/na/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/na/General_cal.acdb \
    vendor/motorola/ocean/proprietary/vendor/etc/acdbdata/na/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/na/Global_cal.acdb \
    vendor/motorola/ocean/proprietary/vendor/etc/acdbdata/na/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/na/Handset_cal.acdb \
    vendor/motorola/ocean/proprietary/vendor/etc/acdbdata/na/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/na/Hdmi_cal.acdb \
    vendor/motorola/ocean/proprietary/vendor/etc/acdbdata/na/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/na/Headset_cal.acdb \
    vendor/motorola/ocean/proprietary/vendor/etc/acdbdata/na/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/na/Speaker_cal.acdb \
    vendor/motorola/ocean/proprietary/vendor/etc/init/android.hardware.biometrics.fingerprint@2.1-service-ocean.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.biometrics.fingerprint@2.1-service-ocean.rc \
    vendor/motorola/ocean/proprietary/vendor/etc/qdcm_calib_data_mipi_mot_vid_csot_720p_622.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_mipi_mot_vid_csot_720p_622.xml \
    vendor/motorola/ocean/proprietary/vendor/etc/qdcm_calib_data_mipi_mot_vid_ofilm_720p_622.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_mipi_mot_vid_ofilm_720p_622.xml \
    vendor/motorola/ocean/proprietary/vendor/etc/qdcm_calib_data_mipi_mot_vid_tianma_720p_622.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_mipi_mot_vid_tianma_720p_622.xml \
    vendor/motorola/ocean/proprietary/vendor/firmware/AbovCapSense.BIN:$(TARGET_COPY_OUT_VENDOR)/firmware/AbovCapSense.BIN \
    vendor/motorola/ocean/proprietary/vendor/firmware/FT8006U_Pramboot.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/FT8006U_Pramboot.bin \
    vendor/motorola/ocean/proprietary/vendor/firmware/cpp_firmware_v1_10_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_10_0.fw \
    vendor/motorola/ocean/proprietary/vendor/firmware/cpp_firmware_v1_12_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_12_0.fw \
    vendor/motorola/ocean/proprietary/vendor/firmware/cpp_firmware_v1_1_1.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_1_1.fw \
    vendor/motorola/ocean/proprietary/vendor/firmware/cpp_firmware_v1_1_6.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_1_6.fw \
    vendor/motorola/ocean/proprietary/vendor/firmware/cpp_firmware_v1_2_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_2_0.fw \
    vendor/motorola/ocean/proprietary/vendor/firmware/cpp_firmware_v1_4_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_4_0.fw \
    vendor/motorola/ocean/proprietary/vendor/firmware/cpp_firmware_v1_5_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_5_0.fw \
    vendor/motorola/ocean/proprietary/vendor/firmware/cpp_firmware_v1_5_1.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_5_1.fw \
    vendor/motorola/ocean/proprietary/vendor/firmware/cpp_firmware_v1_5_2.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_5_2.fw \
    vendor/motorola/ocean/proprietary/vendor/firmware/cpp_firmware_v1_6_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_6_0.fw \
    vendor/motorola/ocean/proprietary/vendor/firmware/cpp_firmware_v1_8_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_8_0.fw \
    vendor/motorola/ocean/proprietary/vendor/firmware/focaltech-ofilm-ft8006u-0e-001-ocean.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/focaltech-ofilm-ft8006u-0e-001-ocean.bin \
    vendor/motorola/ocean/proprietary/vendor/firmware/ilitek-tianma-ILI9881-1c-69-ocean.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/ilitek-tianma-ILI9881-1c-69-ocean.bin \
    vendor/motorola/ocean/proprietary/vendor/firmware/leia_pfp_470.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/leia_pfp_470.fw \
    vendor/motorola/ocean/proprietary/vendor/firmware/leia_pm4_470.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/leia_pm4_470.fw \
    vendor/motorola/ocean/proprietary/vendor/firmware/novatek_ts-csot-NT36672A-180919-07-ocean.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_ts-csot-NT36672A-180919-07-ocean.bin \
    vendor/motorola/ocean/proprietary/vendor/firmware/st21nfc_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/st21nfc_fw.bin \
    vendor/motorola/ocean/proprietary/vendor/firmware/tfa98xx.cnt:$(TARGET_COPY_OUT_VENDOR)/firmware/tfa98xx.cnt

PRODUCT_PACKAGES += \
    sensors.ssc \
    audio.primary.msm8953-moto \
    camera.msm8953 \
    lib_motsensorlistener \
    libactuator_dw9763 \
    libactuator_dw9767 \
    libactuator_lc898217xh \
    libadm \
    libcdsprpc \
    libchromatix_mot_ov12a10_common \
    libchromatix_mot_ov12a10_cpp_hfr_120 \
    libchromatix_mot_ov12a10_cpp_hfr_60 \
    libchromatix_mot_ov12a10_cpp_liveshot \
    libchromatix_mot_ov12a10_cpp_preview \
    libchromatix_mot_ov12a10_cpp_snapshot \
    libchromatix_mot_ov12a10_cpp_snapshot_custom \
    libchromatix_mot_ov12a10_cpp_snapshot_downscale \
    libchromatix_mot_ov12a10_cpp_video \
    libchromatix_mot_ov12a10_default_video \
    libchromatix_mot_ov12a10_hfr_120 \
    libchromatix_mot_ov12a10_hfr_120_3a \
    libchromatix_mot_ov12a10_hfr_60 \
    libchromatix_mot_ov12a10_hfr_60_3a \
    libchromatix_mot_ov12a10_postproc \
    libchromatix_mot_ov12a10_preview \
    libchromatix_mot_ov12a10_snapshot \
    libchromatix_mot_ov12a10_zsl_preview_3a \
    libchromatix_mot_ov12a10_zsl_video_3a \
    libchromatix_mot_s5k3l6_common \
    libchromatix_mot_s5k3l6_cpp_hfr_120 \
    libchromatix_mot_s5k3l6_cpp_hfr_60 \
    libchromatix_mot_s5k3l6_cpp_liveshot \
    libchromatix_mot_s5k3l6_cpp_preview \
    libchromatix_mot_s5k3l6_cpp_snapshot \
    libchromatix_mot_s5k3l6_cpp_snapshot_custom \
    libchromatix_mot_s5k3l6_cpp_video_full \
    libchromatix_mot_s5k3l6_hfr_120 \
    libchromatix_mot_s5k3l6_hfr_120_3a \
    libchromatix_mot_s5k3l6_hfr_60 \
    libchromatix_mot_s5k3l6_hfr_60_3a \
    libchromatix_mot_s5k3l6_postproc \
    libchromatix_mot_s5k3l6_snapshot \
    libchromatix_mot_s5k3l6_video_full \
    libchromatix_mot_s5k3l6_zsl_preview_3a \
    libchromatix_mot_s5k3l6_zsl_video_3a \
    libchromatix_mot_s5k4h7_common \
    libchromatix_mot_s5k4h7_cpp_hfr_120 \
    libchromatix_mot_s5k4h7_cpp_liveshot \
    libchromatix_mot_s5k4h7_cpp_preview \
    libchromatix_mot_s5k4h7_cpp_snapshot \
    libchromatix_mot_s5k4h7_cpp_snapshot_custom \
    libchromatix_mot_s5k4h7_cpp_video_full \
    libchromatix_mot_s5k4h7_hfr_120 \
    libchromatix_mot_s5k4h7_hfr_120_3a \
    libchromatix_mot_s5k4h7_postproc \
    libchromatix_mot_s5k4h7_snapshot \
    libchromatix_mot_s5k4h7_video_full \
    libchromatix_mot_s5k4h7_zsl_preview_3a \
    libchromatix_mot_s5k4h7_zsl_video_3a \
    libchromatix_mot_s5k5e9_common \
    libchromatix_mot_s5k5e9_cpp_hfr_120 \
    libchromatix_mot_s5k5e9_cpp_hfr_60 \
    libchromatix_mot_s5k5e9_cpp_liveshot \
    libchromatix_mot_s5k5e9_cpp_preview \
    libchromatix_mot_s5k5e9_cpp_snapshot \
    libchromatix_mot_s5k5e9_cpp_snapshot_custom \
    libchromatix_mot_s5k5e9_cpp_snapshot_downscale \
    libchromatix_mot_s5k5e9_cpp_video_full \
    libchromatix_mot_s5k5e9_hfr_120 \
    libchromatix_mot_s5k5e9_hfr_120_3a \
    libchromatix_mot_s5k5e9_hfr_60 \
    libchromatix_mot_s5k5e9_hfr_60_3a \
    libchromatix_mot_s5k5e9_postproc \
    libchromatix_mot_s5k5e9_snapshot \
    libchromatix_mot_s5k5e9_video_full \
    libchromatix_mot_s5k5e9_zsl_preview_3a \
    libchromatix_mot_s5k5e9_zsl_video_3a \
    libchromatix_ov12a10_ocean_common \
    libchromatix_ov12a10_ocean_cpp_hfr_120 \
    libchromatix_ov12a10_ocean_cpp_hfr_60 \
    libchromatix_ov12a10_ocean_cpp_liveshot \
    libchromatix_ov12a10_ocean_cpp_preview \
    libchromatix_ov12a10_ocean_cpp_snapshot \
    libchromatix_ov12a10_ocean_cpp_snapshot_custom \
    libchromatix_ov12a10_ocean_cpp_snapshot_downscale \
    libchromatix_ov12a10_ocean_cpp_video \
    libchromatix_ov12a10_ocean_default_video \
    libchromatix_ov12a10_ocean_hfr_120 \
    libchromatix_ov12a10_ocean_hfr_120_3a \
    libchromatix_ov12a10_ocean_hfr_60 \
    libchromatix_ov12a10_ocean_hfr_60_3a \
    libchromatix_ov12a10_ocean_postproc \
    libchromatix_ov12a10_ocean_preview \
    libchromatix_ov12a10_ocean_snapshot \
    libchromatix_ov12a10_ocean_zsl_preview_3a \
    libchromatix_ov12a10_ocean_zsl_video_3a \
    libchromatix_s5k4h7_ocean_common \
    libchromatix_s5k4h7_ocean_cpp_hfr_120 \
    libchromatix_s5k4h7_ocean_cpp_liveshot \
    libchromatix_s5k4h7_ocean_cpp_preview \
    libchromatix_s5k4h7_ocean_cpp_snapshot \
    libchromatix_s5k4h7_ocean_cpp_snapshot_custom \
    libchromatix_s5k4h7_ocean_cpp_video_full \
    libchromatix_s5k4h7_ocean_hfr_120 \
    libchromatix_s5k4h7_ocean_hfr_120_3a \
    libchromatix_s5k4h7_ocean_postproc \
    libchromatix_s5k4h7_ocean_snapshot \
    libchromatix_s5k4h7_ocean_video_full \
    libchromatix_s5k4h7_ocean_zsl_preview_3a \
    libchromatix_s5k4h7_ocean_zsl_video_3a \
    libdepthmapwrapper \
    libflash_pmic \
    libgralloc1 \
    libhal_dbg \
    libjpegdhw \
    libjpegdmahw \
    libjpegehw \
    liblog_vendor \
    libmm-qcamera \
    libmmcamera2_c2d_module \
    libmmcamera2_cpp_module \
    libmmcamera2_frame_algorithm \
    libmmcamera2_iface_modules \
    libmmcamera2_imglib_modules \
    libmmcamera2_is \
    libmmcamera2_isp_modules \
    libmmcamera2_mct \
    libmmcamera2_mct_shimlayer \
    libmmcamera2_pp_buf_mgr \
    libmmcamera2_pproc_modules \
    libmmcamera2_q3a_core \
    libmmcamera2_sensor_modules \
    libmmcamera2_stats_algorithm \
    libmmcamera2_stats_lib \
    libmmcamera2_stats_modules \
    libmmcamera_dbg \
    libmmcamera_depth_map \
    libmmcamera_eebinparse \
    libmmcamera_eeprom_util \
    libmmcamera_eztune_module \
    libmmcamera_facedetection_lib \
    libmmcamera_faceproc \
    libmmcamera_faceproc2 \
    libmmcamera_hdr_gb_lib \
    libmmcamera_imglib \
    libmmcamera_imglib_faceproc_adspstub \
    libmmcamera_interface \
    libmmcamera_isp_abf40 \
    libmmcamera_isp_bcc40 \
    libmmcamera_isp_be_stats44 \
    libmmcamera_isp_bf_stats47 \
    libmmcamera_isp_bg_stats44 \
    libmmcamera_isp_bhist_stats44 \
    libmmcamera_isp_bpc40 \
    libmmcamera_isp_chroma_enhan40 \
    libmmcamera_isp_chroma_suppress40 \
    libmmcamera_isp_clamp_encoder40 \
    libmmcamera_isp_clamp_video40 \
    libmmcamera_isp_clamp_viewfinder40 \
    libmmcamera_isp_color_correct40 \
    libmmcamera_isp_color_xform_encoder40 \
    libmmcamera_isp_color_xform_viewfinder40 \
    libmmcamera_isp_cs_stats44 \
    libmmcamera_isp_demosaic40 \
    libmmcamera_isp_demux40 \
    libmmcamera_isp_fovcrop_encoder40 \
    libmmcamera_isp_fovcrop_viewfinder40 \
    libmmcamera_isp_gamma40 \
    libmmcamera_isp_ihist_stats44 \
    libmmcamera_isp_linearization40 \
    libmmcamera_isp_ltm44 \
    libmmcamera_isp_luma_adaptation40 \
    libmmcamera_isp_mce40 \
    libmmcamera_isp_mesh_rolloff40 \
    libmmcamera_isp_rs_stats44 \
    libmmcamera_isp_scaler_encoder44 \
    libmmcamera_isp_scaler_viewfinder44 \
    libmmcamera_isp_sce40 \
    libmmcamera_isp_sub_module \
    libmmcamera_isp_template \
    libmmcamera_isp_wb40 \
    libmmcamera_mot_dw9763_eeprom \
    libmmcamera_mot_dw9767_eeprom \
    libmmcamera_mot_gt24p64b_eeprom \
    libmmcamera_mot_ov12a10 \
    libmmcamera_mot_ov12a10_eeprom \
    libmmcamera_mot_s5k3l6 \
    libmmcamera_mot_s5k5e9 \
    libmmcamera_mot_s5k5e9_eeprom \
    libmmcamera_paaf_lib \
    libmmcamera_pdaf \
    libmmcamera_pdafcamif \
    libmmcamera_ppbase_module \
    libmmcamera_ppeiscore \
    libmmcamera_quadracfa \
    libmmcamera_s5k4h7 \
    libmmcamera_s5k4h7_eeprom \
    libmmcamera_sat_test_lib \
    libmmcamera_stillmore_lib \
    libmmcamera_sw2d_lib \
    libmmcamera_thread_services \
    libmmcamera_tintless_algo \
    libmmcamera_tintless_bg_pca_algo \
    libmmcamera_tuning \
    libmmcamera_tuning_lookup \
    libmmcamera_vstab_module \
    libmmjpeg \
    libmmjpeg_interface \
    libmmlib2d_interface \
    libmmqjpeg_codec \
    libmmqjpegdma \
    libmot_afd \
    libmot_gpu_mapper \
    libmot_lux_standardization \
    libmotaudioutils \
    libmotimager_utils \
    libqomx_core \
    libqomx_jpegdec \
    libqomx_jpegenc \
    libqomx_jpegenc_pipe \
    libremosaic_daemon \
    libseemore \
    libsensorndkbridge \
    libtinyalsa-moto \
    libtinycompress_vendor \
    libmmieffectswrapper \
    libspeakerbundle \
    com.fingerprints.extension@1.0 \
    charge_only_mode \
    android.hardware.biometrics.fingerprint@2.1-fpcservice
